sudo: false
language: node_js
node_js:
- v7
notifications:
  slack:
    secure: TrcTy4P8jimKr+C6XSRJu47KJxKHypLkJYP8z5SVoeIm9sJdeGefPNEk0NjPsln47NYvj1IxAD7lwq5uK4Ihv6z0scE58xJZhrtL+ViRVuYgTl07QfLN8jbUacnwToOCodtwXBd3p7QbE17mCz8fazFctaNxI/0zfL3SaWdUGXuYe8VJwqIrYJIeYR2DCHd/CZMtdR13e4lWCy+uHKGCwtsu7pMFN8YulfmhKp+kfxlbVhpG2wLKe04MKSrPQDVj3rOV1m/mDBg4xEYAnBjU5bNB0ywloyr1PDcUng8rwsDj5K4XJLpXf7sv3Z7Y2/89hMDvuIi+WZoYSs6kWN7ENsjr9SmgiZ2RS7uFbOv8lKapUJ0hiYePjg7VAQpTKllPWS7QoXBB16W8+wqVDxuvUS1s4UhtZI7vKkpyiFf/JXCWQDmlVfXVQsZycW77HUl9+0Prg047QtQgcIV55B4n+lJzMW3s6ROSWpxvSwuDqigF23wHlQx2zhjFhjLtFiwUVypthUGa5EixjKgfVCU/RqU7OJ9XeYlOr01AerZ8eOvoy2a2jzP394kKnvRqyxwJWj4QQyb4Dil58Bzzo4nA8QRzshd2YpgFQ/AqlABDj7abbU8TfHYsiH8zY448AO3JFo3PA/tS2PQjjOyeArX8cPoK2PTHHw22AgzslHbnrnM=
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
